### ISSUE TITLE
Types clash when using along with @ionic/core@4.2.0 (again again 🙄🙄)

### ISSUE THREAD

**Issue by simonhaenisch** [ionic-team/ionic-pwa-elements#19]
To replace #18.

@mlynch @mhartington this is getting quite frustrating to work with... every time an Ionic interface changes, the `@ionic/pwa-elements` package is blocking us from updating `ionic/core` in our project.

```
[ ERROR ]  TypeScript: node_modules/@ionic/pwa-elements/node_modules/@ionic/core/dist/types/components.d.ts:5142:4
           Subsequent property declarations must have the same type. Property ''IonRange'' must be of type 'IonRange',
           but here has type 'IonRange'.

   L5141:  'IonRadio': Components.IonRadio;
   L5142:  'IonRange': Components.IonRange;
   L5143:  'IonRefresherContent': Components.IonRefresherContent;

[ ERROR ]  TypeScript: node_modules/@ionic/pwa-elements/node_modules/@ionic/core/dist/types/components.d.ts:5208:4
           Subsequent property declarations must have the same type. Property ''ion-img'' must be of type
           'IonImgAttributes', but here has type 'IonImgAttributes'.

   L5207:  'ion-header': Components.IonHeaderAttributes;
   L5208:  'ion-img': Components.IonImgAttributes;
   L5209:  'ion-infinite-scroll-content': Components.IonInfiniteScrollContentAttributes;

[ ERROR ]  TypeScript: node_modules/@ionic/pwa-elements/node_modules/@ionic/core/dist/types/components.d.ts:5242:4
           Subsequent property declarations must have the same type. Property ''ion-range'' must be of type
           'IonRangeAttributes', but here has type 'IonRangeAttributes'.

   L5241:  'ion-radio': Components.IonRadioAttributes;
   L5242:  'ion-range': Components.IonRangeAttributes;
   L5243:  'ion-refresher-content': Components.IonRefresherContentAttributes;
```

---

May I suggest removing ionic from the dependencies (there's only one interface imported anyway), and adding

```json
{
  "peerDependencies": {
    "@ionic/core": "^4.0.0"
  }
}
```

to `package.json`?

**Comment by MCanhisares** [comment]
Do we have an update on this?

**Comment by kerosin** [comment]
Workaround for us was to use [selective dependency resolutions](https://yarnpkg.com/lang/en/docs/selective-version-resolutions/) with yarn

_package.json_
`  "resolutions": {
    "@ionic/core": "4.3.0"
  },`

**Comment by corysmc** [comment]
Ran into this issue today as well.

**Comment by simonhaenisch** [comment]
Just found a solution to get around this... you can add a path mapping for `@ionic/core` to `tsconfig.json` so that it resolves `@ionic/core` to the same path for both your project and `@ionic/pwa-elements`:

```js
{
  "compilerOptions": {
    // ...

    "baseUrl": ".", // needed to make "paths" work
    "paths": {
      "@ionic/core": ["node_modules/@ionic/core"]
    }
  }
}
```

---

I have a suggestion for a better and cleaner solution though, that would be a bit of a breaking change but solve this long-term: make Ionic an external dependency. That would mean that when including `@ionic/pwa-elements` as a script, `@ionic/core` would have to be included first. When using it in a project, `@ionic/core` should be a peer dependency. Because of how Ionic components are lazy-loaded, I think this approach would work fine. If wanted, I can try and make a PR for that (/cc @mlynch @mhartington)?

**Comment by corysmc** [comment]
Thanks @simonhaenisch that fixes it for me!

**Comment by mlynch** [comment]
Does changing this to use `peerDependencies` resolve it?

**Comment by mlynch** [comment]
Hey all, we're working on some changes that should permanently fix this. Stay tuned.

**Comment by simonhaenisch** [comment]
Just saw that you removed Ionic completely... that's another way of making it work 😄 I liked the idea of it being an extension of Ionic (i. e. it would be able to use `ion-toast`), however there doesn't seem to be a simple way of maintaining that.

**Comment by jcesarmobile** [comment]
as 1.1.0 doesn't use @ionic/core, this can be closed

**Comment by SoftronetBithin** [comment]
> Just found a solution to get around this... you can add a path mapping for `@ionic/core` to `tsconfig.json` so that it resolves `@ionic/core` to the same path for both your project and `@ionic/pwa-elements`:
> 
> ```js
> {
>   "compilerOptions": {
>     // ...
> 
>     "baseUrl": ".", // needed to make "paths" work
>     "paths": {
>       "@ionic/core": ["node_modules/@ionic/core"]
>     }
>   }
> }
> ```
> 
> I have a suggestion for a better and cleaner solution though, that would be a bit of a breaking change but solve this long-term: make Ionic an external dependency. That would mean that when including `@ionic/pwa-elements` as a script, `@ionic/core` would have to be included first. When using it in a project, `@ionic/core` should be a peer dependency. Because of how Ionic components are lazy-loaded, I think this approach would work fine. If agreed, I can try and make a PR for that (/cc @mlynch @mhartington)?

Thanks @simonhaenisch . It works for me.

**Comment by mlynch** [comment]
@simonhaenisch we do want to get back to that point, and it _should_ work. Just given everyone's time it wasn't going to work before we hit 1.0 so we needed to punt on that. There's some compiler work still to be done first.
